[settings]
lockfile = true

[tool_alias]
binaryen = "aqua:WebAssembly/binaryen"
wasi-sdk = "github:WebAssembly/wasi-sdk"

[tools]
wasmtime = "49.0.1"
shellcheck = "0.11.0"
binaryen = "133"

[tools.wasi-sdk]
version = "34"
version_prefix = "wasi-sdk-"
# mise hides system build tools (cc, ar, etc) in the default.
# However, these tools are necessary to build the host binary.
# The below setting drops every binary in wasi-sdk from PATH;
# therefore, the system build tools are still available.
filter_bins = ["none"]
