[settings]
lockfile = true

[tool_alias]
binaryen = "aqua:WebAssembly/binaryen"
wasi-sdk = "github:WebAssembly/wasi-sdk"

[tools]
wasmtime = "49.0.1"
shellcheck = "0.11.0"
binaryen = "133"
wasi-sdk = {
  version = "34",
  version_prefix = "wasi-sdk-",
  asset_pattern = 'wasi-sdk-{{ version }}.0-{{ arch(x64="x86_64" )}}-{{ os() }}.tar.gz'
}
