#!/bin/sh

# Generate cows_embedded.h from the cowfiles given as arguments.
#
# Usage: embed-cows.sh > cows_embedded.h
#
# Each file becomes a byte array in argument order, so the caller passes them sorted by name.
#
# The comments and blank lines above the heredoc are dropped, since the parser ignores them anyway.
# Everything from the heredoc line on is copied untouched;
# vader.cow draws a line of its own art that starts with "#".

set -eu

# strip <file>: the cowfile without the comments and blank lines that precede its heredoc.
strip() {
  awk '
    body { print; next }
    /\$the_cow[ \t]*=[ \t]*<</ { body = 1; print; next }
    /^[ \t]*#/ || /^[ \t]*$/ { next }
    { print }
  ' "$1"
}

printf '/* Generated by tools/embed-cows.sh; do not edit. */\n'
printf 'struct embedded_cow {\n'
printf '  const char *name;\n'
printf '  const unsigned char *data;\n'
printf '  unsigned int len;\n'
printf '};\n\n'

i=0
for f in "$@"; do
  printf 'static const unsigned char cow_data_%d[] = {\n' "$i"
  strip "$f" | od -An -v -tu1 |
    awk '{ line = ""; for (j = 1; j <= NF; j++) line = line $j ","; print line }'
  printf '};\n'
  i=$((i + 1))
done

printf '\nstatic const struct embedded_cow embedded_cows[] = {\n'
i=0
for f in "$@"; do
  base=$(basename "$f")
  printf '  { "%s", cow_data_%d, sizeof cow_data_%d },\n' "$base" "$i" "$i"
  i=$((i + 1))
done
printf '};\n'
