#!/usr/bin/env perl

# Generate cows_embedded.h from the cowfiles given as arguments.
#
# Usage: embed-cows.pl cows/*.cow > cows_embedded.h
#
# The cowfiles are joined in argument order, so the caller passes them sorted by name.
# The joined text is compressed as LZSS, which cowsay.c expands on first use;
# plain, it would be about 17 kB more of the binary.
#
# The comments and blank lines above the heredoc are dropped, since the parser ignores them anyway.
# Everything from the heredoc line on is copied untouched;
# vader.cow draws a line of its own art that starts with "#".

use strict;
use warnings;

# The format cows_text in cowsay.c reads: a flag byte leads each group of eight items,
# low bit first. A clear bit is one literal byte.
# A set bit is a two-byte big-endian reference: (distance - 1) << 4 | (length - 3).
my $WINDOW = 4096;
my ($MIN_MATCH, $MAX_MATCH) = (3, 18);

sub strip {
  my $path = shift;
  open my $fh, '<:raw', $path or die "embed-cows.pl: $path: $!\n";
  my ($out, $body) = ('', 0);
  while (my $line = <$fh>) {
    $body ||= $line =~ /\$the_cow[ \t]*=[ \t]*<</;
    next if !$body && $line =~ /^[ \t]*(?:#|$)/;
    $out .= $line;
  }
  return $out;
}

# Greedy parse: at each position, the longest match in the window, the nearest among equals.
sub compress {
  my $text = shift;
  my ($out, %seen, @items) = ('');
  my $n = length $text;
  my $i = 0;
  while ($i < $n) {
    my ($best, $distance) = (0, 0);
    for my $j (reverse @{ $seen{substr $text, $i, $MIN_MATCH} // [] }) {
      last if $i - $j > $WINDOW;
      my $len = 0;
      $len++ while $len < $MAX_MATCH && $i + $len < $n
        && substr($text, $j + $len, 1) eq substr($text, $i + $len, 1);
      ($best, $distance) = ($len, $i - $j) if $len > $best;
    }
    my $step = $best >= $MIN_MATCH ? $best : 1;
    push @items, $best >= $MIN_MATCH ? [$distance, $best] : substr $text, $i, 1;
    push @{ $seen{substr $text, $_, $MIN_MATCH} }, $_ for $i .. $i + $step - 1;
    $i += $step;
  }
  while (my @group = splice @items, 0, 8) {
    my ($flags, $body) = (0, '');
    for my $bit (0 .. $#group) {
      if (ref $group[$bit]) {
        my ($distance, $len) = @{ $group[$bit] };
        $flags |= 1 << $bit;
        $body .= pack 'n', ($distance - 1) << 4 | ($len - $MIN_MATCH);
      } else {
        $body .= $group[$bit];
      }
    }
    $out .= chr($flags) . $body;
  }
  return $out;
}

sub expand {
  my ($packed, $n) = @_;
  my ($text, $i) = ('', 0);
  while (length $text < $n) {
    my $flags = ord substr $packed, $i++, 1;
    for my $bit (0 .. 7) {
      last if length $text >= $n;
      if ($flags >> $bit & 1) {
        my $v = unpack 'n', substr $packed, $i, 2;
        $i += 2;
        $text .= substr $text, -(($v >> 4) + 1), 1 for 1 .. ($v & 15) + $MIN_MATCH;
      } else {
        $text .= substr $packed, $i++, 1;
      }
    }
  }
  return $text;
}

my @names = map { m{([^/]+)$} } @ARGV;
my @texts = map { strip($_) } @ARGV;
my $text = join '', @texts;
my $packed = compress($text);
expand($packed, length $text) eq $text or die "embed-cows.pl: the compressed text does not expand back\n";

print <<"HEADER";
/* Generated by tools/embed-cows.pl; do not edit. */
struct embedded_cow {
  const char *name;
  unsigned int offset, len;
};

#define COWS_TEXT_LEN @{[length $text]}

static const unsigned char cows_lzss[] = {
HEADER
my @bytes = unpack 'C*', $packed;
while (my @line = splice @bytes, 0, 16) {
  print join(',', @line), ",\n";
}
print "};\n\nstatic const struct embedded_cow embedded_cows[] = {\n";
my $offset = 0;
for my $k (0 .. $#names) {
  printf "  { \"%s\", %d, %d },\n", $names[$k], $offset, length $texts[$k];
  $offset += length $texts[$k];
}
print "};\n";
printf STDERR "%d bytes of cowfiles in %d bytes\n", length $text, length $packed;
