#!/bin/sh
# Generate cows_embedded.h from the cowfiles given as arguments.
# Each file becomes a byte array; the table is emitted in argument order,
# so the caller passes the files sorted by name.
set -eu

printf '/* Generated by tools/embed-cows.sh; do not edit. */\n'
printf 'struct embedded_cow {\n'
printf '    const char *name;\n'
printf '    const unsigned char *data;\n'
printf '    unsigned int len;\n'
printf '};\n\n'

i=0
for f in "$@"; do
    printf 'static const unsigned char cow_data_%d[] = {\n' "$i"
    od -An -v -tu1 "$f" | awk '{ line = ""; for (j = 1; j <= NF; j++) line = line $j ","; print line }'
    printf '};\n'
    i=$((i + 1))
done

printf '\nstatic const struct embedded_cow embedded_cows[] = {\n'
i=0
for f in "$@"; do
    base=$(basename "$f")
    printf '    { "%s", cow_data_%d, sizeof cow_data_%d },\n' "$base" "$i" "$i"
    i=$((i + 1))
done
printf '};\n'
