#!/usr/bin/env perl

# Generate unicode_tables.h from the Unicode Character Database.
#
# Usage: gen-unicode-tables.pl [ucd-directory] > unicode_tables.h
#
# The header is a build artifact, regenerated whenever the vendored files or this script change.
# Nothing here touches the network; tools/fetch-ucd.sh moves the vendored files to a new version.
# Five files feed it: EastAsianWidth and DerivedGeneralCategory (display width),
# GraphemeBreakProperty and DerivedCoreProperties (cluster boundaries),
# and emoji-data (the emoji width rules).

use strict;
use warnings;

my $UCD = shift // 'ucd';

# Grapheme_Cluster_Break classes, in the order the C side expects.
my @GCB = qw(Other CR LF Control Extend ZWJ Regional_Indicator Prepend SpacingMark L V T LV LVT);
my %GCB_ID = map { $GCB[$_] => $_ } 0 .. $#GCB;

# Width classes: 0 normal, 1 wide, 2 ambiguous, 3 zero.
my %WIDTH_ID = (normal => 0, wide => 1, ambiguous => 2, zero => 3);

# Indic_Conjunct_Break classes for GB9c: 0 none, 1 Consonant, 2 Extend, 3 Linker.
my %INCB_ID = (None => 0, Consonant => 1, Extend => 2, Linker => 3);

sub read_ucd {
  my $name = shift;
  open my $fh, '<', "$UCD/$name" or die "gen-unicode-tables.pl: $UCD/$name: $!\n";
  local $/;
  return <$fh>;
}

# Every UCD file names itself and its version on the first line,
# so the generated header can state what it was built from.
sub ucd_version {
  my ($first) = split /\n/, read_ucd('EastAsianWidth.txt');
  my ($version) = $first =~ /-([0-9]+\.[0-9]+\.[0-9]+)\.txt/
    or die "gen-unicode-tables.pl: EastAsianWidth.txt names no version\n";
  return $version;
}
my $VERSION = ucd_version();

# Parse a UCD file of "range; value" lines into [lo, hi, value] triples.
sub parse {
  my ($body, $want) = @_;
  my @out;
  for my $line (split /\n/, $body) {
    $line =~ s/#.*//;
    next unless $line =~ /\S/;
    my ($range, @fields) = map { s/^\s+|\s+$//gr } split /;/, $line;
    my $value = join '; ', @fields;
    next if $want && !$want->{$fields[0] // ''};
    my ($lo, $hi) = $range =~ /^([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?$/ or next;
    push @out, [hex $lo, hex($hi // $lo), $value, $fields[0] // ''];
  }
  return @out;
}

my %props;    # codepoint -> [gcb, width, extpict, emojipres, incb]
sub set_prop {
  my ($lo, $hi, $index, $value) = @_;
  for my $cp ($lo .. $hi) {
    $props{$cp} //= [0, 0, 0, 0, 0];
    $props{$cp}[$index] = $value;
  }
}

for my $r (parse(read_ucd('GraphemeBreakProperty.txt'))) {
  my $id = $GCB_ID{$r->[3]} // next;
  set_prop($r->[0], $r->[1], 0, $id);
}
for my $r (parse(read_ucd('EastAsianWidth.txt'))) {
  my $w = $r->[3] eq 'W' || $r->[3] eq 'F' ? $WIDTH_ID{wide}
        : $r->[3] eq 'A' ? $WIDTH_ID{ambiguous}
        : next;
  set_prop($r->[0], $r->[1], 1, $w);
}
# A default-ignorable or non-spacing mark occupies no column of its own.
for my $r (parse(read_ucd('DerivedGeneralCategory.txt'), {map { $_ => 1 } qw(Mn Me Cf)})) {
  set_prop($r->[0], $r->[1], 1, $WIDTH_ID{zero});
}
my %emoji = (Extended_Pictographic => 2, Emoji_Presentation => 3);
for my $r (parse(read_ucd('emoji-data.txt'), {map { $_ => 1 } keys %emoji})) {
  set_prop($r->[0], $r->[1], $emoji{$r->[3]}, 1);
}
for my $r (parse(read_ucd('DerivedCoreProperties.txt'))) {
  my ($value) = $r->[2] =~ /^InCB;\s*(\w+)$/ or next;
  my $id = $INCB_ID{$value} // next;
  set_prop($r->[0], $r->[1], 4, $id);
}

# Pack each codepoint's properties into one 16-bit word, then merge equal neighbours into ranges.
sub word {
  my $p = shift // [0, 0, 0, 0, 0];
  return $p->[0] | ($p->[1] << 4) | ($p->[2] << 6) | ($p->[3] << 7) | ($p->[4] << 8);
}
my @ranges;
for my $cp (sort { $a <=> $b } keys %props) {
  my $w = word($props{$cp});
  next if $w == 0;
  if (@ranges && $ranges[-1][1] == $cp - 1 && $ranges[-1][2] == $w) {
    $ranges[-1][1] = $cp;
  } else {
    push @ranges, [$cp, $cp, $w];
  }
}

print <<"HEADER";
/* Generated by tools/gen-unicode-tables.pl from the vendored UCD $VERSION; do not edit. */

/* Grapheme_Cluster_Break classes, the low four bits of a property word. */
enum {
HEADER
printf "  GCB_%s = %d,\n", uc $GCB[$_], $_ for 0 .. $#GCB;
print <<'HEADER';
};

/* The remaining bits: width class, the two emoji properties, and Indic_Conjunct_Break for GB9c. */
#define UPROP_GCB(w) ((w) & 0xf)
#define UPROP_WIDTH(w) (((w) >> 4) & 0x3)
#define UPROP_EXTPICT(w) (((w) >> 6) & 0x1)
#define UPROP_EMOJIPRES(w) (((w) >> 7) & 0x1)
#define UPROP_INCB(w) (((w) >> 8) & 0x3)

enum { UWIDTH_NORMAL = 0, UWIDTH_WIDE = 1, UWIDTH_AMBIGUOUS = 2, UWIDTH_ZERO = 3 };
enum { INCB_NONE = 0, INCB_CONSONANT = 1, INCB_EXTEND = 2, INCB_LINKER = 3 };

/* Codepoints with no property of interest are absent; a lookup that misses reads as zero.
 * A range is its first codepoint, the count after it, and the property word,
 * packed into eight bytes. */
struct urange {
  unsigned int lo;
  unsigned short extra;
  unsigned short props;
};

HEADER
# A range longer than the count field holds is split, which costs a handful of entries.
my @packed;
for my $r (@ranges) {
  my ($lo, $hi, $w) = @$r;
  while ($lo <= $hi) {
    my $end = $hi - $lo > 0xffff ? $lo + 0xffff : $hi;
    push @packed, [$lo, $end - $lo, $w];
    $lo = $end + 1;
  }
}
printf "static const struct urange unicode_ranges[] = {\n";
printf "  { 0x%04X, %d, 0x%03X },\n", @$_ for @packed;
printf "};\n";
printf STDERR "%d ranges\n", scalar @packed;
